version: 0.0 
os: linux
files:
  - source: /
    destination: /home/ubuntu/app_simple_chat/ezops-test-bedatty/
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: root